import { Language } from './types';

export const YEARS = Array.from({ length: 10 }, (_, i) => new Date().getFullYear() - i);
export const MONTHS = [
  { fr: 'Janvier', ar: 'يناير', value: 1 },
  { fr: 'Février', ar: 'فبراير', value: 2 },
  { fr: 'Mars', ar: 'مارس', value: 3 },
  { fr: 'Avril', ar: 'أبريل', value: 4 },
  { fr: 'Mai', ar: 'ماي', value: 5 },
  { fr: 'Juin', ar: 'يونيو', value: 6 },
  { fr: 'Juillet', ar: 'يوليوز', value: 7 },
  { fr: 'Août', ar: 'غشت', value: 8 },
  { fr: 'Septembre', ar: 'شتنبر', value: 9 },
  { fr: 'Octobre', ar: 'أكتوبر', value: 10 },
  { fr: 'Novembre', ar: 'نونبر', value: 11 },
  { fr: 'Décembre', ar: 'دجنبر', value: 12 },
];

export const translations = {
  [Language.FR]: {
    headerTitle: 'Simpl-IR',
    headerSubtitle: 'Impôt sur le revenu',
    professionals: 'Professionnels',
    pageTitle: 'Prélèvement sur revenus salariaux et assimilés',
    welcome: 'Bienvenue RFN',
    taxId: 'Identifiant fiscal',
    companyName: '4GESTION ACADEMY',
    fiscalIdValue: '660912300',
    returnToHome: "Retour à l'accueil",
    logout: 'Se déconnecter',
    needHelp: "Besoin d'aide?",
    contact: 'Contact',
    newPayment: 'Nouveau versement',
    year: 'Année',
    month: 'Mois',
    createPayment: 'Créer un versement',
    pendingItemsList: 'Liste des éléments en suspens',
    noPendingItems: 'Aucun élément correspondant à ces critères n’a été trouvé.',
    fiscalYear: 'Année fiscale',
    paymentMonth: 'Mois du versement',
    paymentType: 'Type de versement',
    formStatus: 'État du formulaire',
    actions: 'Actions',
    edit: 'Modifier',
    delete: 'Supprimer',
    exportExcel: 'Exporter Excel / Smart EDI',
    printSummary: 'Imprimer le récapitulatif',
    declarationDetails: 'Détail de la déclaration',
    calculateAmountToPay: 'Calcul du montant à payer',
    totalRemuneration: 'Montant global des rémunérations versées',
    correspondingWithholdings: 'Montant des retenues correspondantes',
    alreadyPaid: 'Somme des montants en principal des paiements déjà versés',
    calculate: 'Calculer',
    principalAmountToPay: 'Montant en principal à payer',
    penalty: 'Pénalité',
    lateFees: 'Majorations de retard',
    totalAmountToPay: 'Montant total à verser',
    saveDraft: 'Enregistrer',
    submitDeclaration: 'Déposer',
    print: 'Imprimer',
    abandon: 'Abandonner',
    back: 'Retour',
    initial: 'Initial',
    corrective: 'Correctif',
    draft: 'Brouillon',
    validated: 'Validé',
    paid: 'Payé',
    // Payment Page
    paymentDetails: 'Détail du paiement',
    paymentMode: 'Mode de paiement',
    bankAccount: 'Compte bancaire',
    amountToDebit: 'Montant à prélever',
    validatePayment: 'Valider le paiement',
    bankTransfer: 'Ordre de prélèvement bancaire',
    // Receipt Page
    paymentSuccess: 'Paiement effectué avec succès',
    paymentReceipt: 'Quittance de paiement',
    declarationSummary: 'Récapitulatif de la déclaration',
    downloadDeclaration: 'Télécharger la déclaration (PDF)',
    downloadReceipt: 'Télécharger la quittance (PDF)',
    backToDashboard: 'Retour au tableau de bord',
    // New UI Elements
    Home: 'Accueil',
    Teleservices: 'TÉLÉSERVICES SIMPL',
    ProfessionalsSpace: 'Espace professionnels',
    SimplAdhesion: 'Simpl-Adhésion',
    SimplIS: 'Simpl-IS',
    SimplTVA: 'Simpl-TVA',
    SimplIR: 'Simpl-IR',
    SimplAutres: 'Simpl-Autres taxes',
    AccessSimplIR: 'Accédez au Simpl-IR',
    GuideRevenuGlobal: 'GUIDE DE DECLARATION DU REVENU GLOBAL',
    GuideDTS: 'GUIDE DE DECLARATION DES TRAITEMENTS ET SALAIRES - DTS',
  },
  [Language.AR]: {
    headerTitle: 'Simpl-IR',
    headerSubtitle: 'الضريبة على الدخل',
    professionals: 'المهنيين',
    pageTitle: 'دخول الأجور والدخول المعتبرة في حكمها',
    welcome: 'مرحبا RFN',
    taxId: 'المعرف الضريبي',
    companyName: 'أكاديمية 4GESTION',
    fiscalIdValue: '660912300',
    returnToHome: 'العودة إلى الإستقبال',
    logout: 'تسجيل الخروج',
    needHelp: 'تحتاج مساعدة؟',
    contact: 'اتصال',
    newPayment: 'أداء جديد',
    year: 'سنة',
    month: 'شهر',
    createPayment: 'القيام بأداء',
    pendingItemsList: 'لائحة العناصر في حالة انتظار',
    noPendingItems: 'لم يتم العثور على أي عنصر مطابق لهذه المعايير.',
    fiscalYear: 'سنة مالية',
    paymentMonth: 'شهر الأداء',
    paymentType: 'نوع الأداء',
    formStatus: 'حالة النموذج',
    actions: 'إجراءات',
    edit: 'تعديل',
    delete: 'حذف',
    exportExcel: 'تصدير Excel / Smart EDI',
    printSummary: 'طباعة الملخص',
    declarationDetails: 'تفاصيل الإقرار',
    calculateAmountToPay: 'حساب المبلغ الواجب دفعه',
    totalRemuneration: 'المبلغ الإجمالي للأجور المدفوعة',
    correspondingWithholdings: 'مبلغ الاقتطاعات المقابلة',
    alreadyPaid: 'مجموع المبالغ الأصلية للدفعات التي سبق دفعها',
    calculate: 'حساب',
    principalAmountToPay: 'المبلغ الأصلي الواجب دفعه',
    penalty: 'غرامة',
    lateFees: 'زيادات عن التأخير',
    totalAmountToPay: 'المجموع الذي يجب أن يؤدى',
    saveDraft: 'حفظ',
    submitDeclaration: 'إيداع',
    print: 'طباعة',
    abandon: 'إلغاء',
    back: 'رجوع',
    initial: 'أولي',
    corrective: 'تصحيحي',
    draft: 'مسودة',
    validated: 'مصادق عليه',
    paid: 'مدفوع',
     // Payment Page
    paymentDetails: 'تفاصيل الدفع',
    paymentMode: 'طريقة الدفع',
    bankAccount: 'حساب بنكي',
    amountToDebit: 'المبلغ المراد خصمه',
    validatePayment: 'تأكيد الدفع',
    bankTransfer: 'أمر خصم بنكي',
    // Receipt Page
    paymentSuccess: 'تم الدفع بنجاح',
    paymentReceipt: 'إيصال الدفع',
    declarationSummary: 'ملخص الإقرار',
    downloadDeclaration: 'تحميل الإقرار (PDF)',
    downloadReceipt: 'تحميل الإيصال (PDF)',
    backToDashboard: 'العودة إلى لوحة التحكم',
    // New UI Elements
    Home: 'الرئيسية',
    Teleservices: 'الخدمات الإلكترونية SIMPL',
    ProfessionalsSpace: 'فضاء المهنيين',
    SimplAdhesion: 'الانخراط Simpl',
    SimplIS: 'الضريبة على الشركات Simpl',
    SimplTVA: 'الضريبة على القيمة المضافة Simpl',
    SimplIR: 'الضريبة على الدخل Simpl',
    SimplAutres: 'ضرائب أخرى Simpl',
    AccessSimplIR: 'الولوج إلى Simpl-IR',
    GuideRevenuGlobal: 'دليل التصريح بالدخل الإجمالي',
    GuideDTS: 'دليل التصريح بالأجور والرواتب',
  },
};